import {
  ApplicationConfig,
  importProvidersFrom,
  isDevMode,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideServiceWorker } from '@angular/service-worker';
import { provideStegApi, resolveStegApiUrl } from 'shared-data-access';
import {
  Activity,
  Ambulance,
  ArrowRight,
  BadgeCheck,
  Bell,
  CalendarDays,
  Camera,
  CarFront,
  Check,
  CircleCheckBig,
  ChevronDown,
  ChevronRight,
  CircleUserRound,
  ClipboardCheck,
  ClipboardPen,
  Clock3,
  Copy,
  FileText,
  Flame,
  Gauge,
  History,
  Info,
  ListChecks,
  LocateFixed,
  LockKeyhole,
  LogOut,
  LucideAngularModule,
  MapPin,
  MapPinCheck,
  MessageCircle,
  Navigation,
  PackagePlus,
  Phone,
  Radio,
  RadioTower,
  RefreshCw,
  Route,
  Save,
  ScanSearch,
  Search,
  Send,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Smartphone,
  TriangleAlert,
  Truck,
  UsersRound,
  Wifi,
  WifiOff,
  Wrench,
  X,
  Zap,
  ZapOff,
} from 'lucide-angular';

import { routes } from './app.routes';

export const maintenanceIcons = {
  Activity,
  Ambulance,
  ArrowRight,
  BadgeCheck,
  Bell,
  CalendarDays,
  Camera,
  CarFront,
  Check,
  CircleCheckBig,
  ChevronDown,
  ChevronRight,
  CircleUserRound,
  ClipboardCheck,
  ClipboardPen,
  Clock3,
  Copy,
  FileText,
  Flame,
  Gauge,
  History,
  Info,
  ListChecks,
  LocateFixed,
  LockKeyhole,
  LogOut,
  MapPin,
  MapPinCheck,
  MessageCircle,
  Navigation,
  PackagePlus,
  Phone,
  Radio,
  RadioTower,
  RefreshCw,
  Route,
  Save,
  ScanSearch,
  Search,
  Send,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Smartphone,
  TriangleAlert,
  Truck,
  UsersRound,
  Wifi,
  WifiOff,
  Wrench,
  X,
  Zap,
  ZapOff,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideStegApi(resolveStegApiUrl()),
    importProvidersFrom(LucideAngularModule.pick(maintenanceIcons)),
    provideServiceWorker('ngsw-worker.js', {
      enabled:
        !isDevMode() &&
        typeof window !== 'undefined' &&
        window.isSecureContext &&
        (window.location.protocol === 'https:' ||
          window.location.hostname === 'localhost' ||
          window.location.hostname === '127.0.0.1'),
      registrationStrategy: 'registerImmediately',
    }),
  ],
};
