FROM node:24-alpine AS build
WORKDIR /workspace

COPY package.json package-lock.json ./
RUN npm install --no-audit --no-fund

COPY angular.json tsconfig.json ./
COPY apps ./apps
COPY libs ./libs
RUN npx ng build shared-data-access

ARG APP_NAME
RUN npx ng build "${APP_NAME}" --configuration production

FROM nginx:1.29-alpine
ARG APP_NAME
COPY infra/docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/dist/${APP_NAME}/browser /usr/share/nginx/html
EXPOSE 80
