import {
  ApplicationConfig,
  importProvidersFrom,
  isDevMode,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideStegApi, resolveStegApiUrl } from 'shared-data-access';
import { routes } from './app.routes';
import { provideServiceWorker } from '@angular/service-worker';
import {
  Activity,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  BellOff,
  Cable,
  CalendarCheck2,
  CalendarClock,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  ClipboardCheck,
  Clock3,
  ClockArrowUp,
  CloudOff,
  ExternalLink,
  FileCheck2,
  Flame,
  Gauge,
  Headphones,
  Home,
  House,
  HousePlug,
  Layers3,
  LayoutDashboard,
  ListChecks,
  LocateFixed,
  LogOut,
  LucideAngularModule,
  Map,
  MapPin,
  MapPinCheck,
  MessageSquareDashed,
  MessageSquarePlus,
  MessageSquareWarning,
  MessagesSquare,
  Minus,
  Navigation,
  PhoneCall,
  Plus,
  Radio,
  RefreshCw,
  Send,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Timer,
  TriangleAlert,
  Users,
  Wrench,
  X,
  Zap,
  ZapOff,
} from 'lucide-angular';

export const citizenIcons = {
  Activity,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  BellOff,
  Cable,
  CalendarCheck2,
  CalendarClock,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  ClipboardCheck,
  Clock3,
  ClockArrowUp,
  CloudOff,
  ExternalLink,
  FileCheck2,
  Flame,
  Gauge,
  Headphones,
  Home,
  House,
  HousePlug,
  Layers3,
  LayoutDashboard,
  ListChecks,
  LocateFixed,
  LogOut,
  Map,
  MapPin,
  MapPinCheck,
  MessageSquareDashed,
  MessageSquarePlus,
  MessageSquareWarning,
  MessagesSquare,
  Minus,
  Navigation,
  PhoneCall,
  Plus,
  Radio,
  RefreshCw,
  Send,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Timer,
  TriangleAlert,
  Users,
  Wrench,
  X,
  Zap,
  ZapOff,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideStegApi(resolveStegApiUrl()),
    importProvidersFrom(LucideAngularModule.pick(citizenIcons)),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerImmediately',
    }),
  ],
};
